name: ShellCheck

on:
  workflow_dispatch:
  push:
    paths:
      - '**.sh'
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review]
    paths:
      - '**.sh'
  
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x
